<a href="https://colab.research.google.com/github/pm-Youngchan/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_6%EA%B0%95_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 6강 - 데이터 전처리 1

### 6-1 데이터 훑어보기

In [5]:
import pandas as pd
import numpy as np

data = {
    'name': ['김민수', '이지영', '박준호', '최서연', '정도윤'],
    'age': [25, 30, 28, 22, 35],
    'city': ['서울', '부산', '인천', '서울', '대전'],
    'score': [90, 85, 95, 80, np.nan]
}
df = pd.DataFrame(data)

# 데이터 측정
# df.describe()

# 모든 데이터 타입 측정
# df.describe(include='all')

# 수치형 데이터 측정
df.describe(include=[np.number])

# 범주형 데이터 측정
df.describe(include=['object'])

# 특정 열 분석
df['score'].describe()

count     4.000000
mean     87.500000
std       6.454972
min      80.000000
25%      83.750000
50%      87.500000
75%      91.250000
max      95.000000
Name: score, dtype: float64

### 6-2 DataFrame 열 선택 및 **조작**

In [15]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)

# 특정 열 선택
#1개 df['이름']
#2개 df[['이름','학과']]
selected_col = df[['이름','학과','학점']]
selected_col

# DataFrame 열순서 변경
reordered_cols = df[['학과','이름','학년','학점','동아리']]
reordered_cols

# DataFrame 열이름 변경
df_renamed = df.rename(columns={'이름': '학생명', '학점':'y'})
df_renamed

   학생명  학년    y     학과    동아리
0  김철수   1  4.2  컴퓨터공학  프로그래밍
1  이영희   2  3.8    경영학   독서토론
2  박민수   3  4.5   전자공학   로봇공학
3  최지훈   4  3.9     의학   봉사활동
4  정소희   2  3.5    심리학   음악감상

### 6-3 DataFrame 행 선택

In [33]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

#DataFrame 인덱스 지정 - 행을 지정하려고 할 때 사용
df = pd.DataFrame(data)
df = df.set_index('이름')
df

#DataFrame 행 선택
df.loc['김철수']
df.loc[['김철수','정소희']]
#슬라이싱
df.loc['이영희':'최지훈']

#DataFrame 위치 기반 행 선택
df.iloc[1]
df.iloc[[3,4]]
df.iloc[1:4]

#DataFrame 조건 기반 선택, boolean 이용해 데이터를 가져옴
df.loc[[True, False,False, True, False]]

#print(df['학점'])
df.loc[df['학점'] >= 4.0]

print(df[['학년', '학점']])
df[df['학년'] == 2]
df[(df['학년'] == 2) & (df['학점'] >= 3.7)]

     학년   학점
이름
김철수   1  4.2
이영희   2  3.8
박민수   3  4.5
최지훈   4  3.9
정소희   2  3.5

     학년   학점   학과   동아리
이름
이영희   2  3.8  경영학  독서토론

### 6-4 DataFrame 정렬

In [43]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

#DataFrame 인덱스 지정 - 1줄로 작성
df = pd.DataFrame(data).set_index('이름')
df

#DataFrame 단일 열 오름차순, 내림차순 정렬
df.sort_values(by='학점')
df.sort_values(by='학점', ascending=False)

#DataFrame 복수 열 오름차순, 내림차순 정렬
df.sort_values(by=['학년', '학점'], ascending=[False, False])

#DataFrame 인덱스 기준으로 오른차순, 내림차순 정렬
df.sort_index(ascending=False)

     학년   학점     학과    동아리
이름
최지훈   4  3.9     의학   봉사활동
정소희   2  3.5    심리학   음악감상
이영희   2  3.8    경영학   독서토론
박민수   3  4.5   전자공학   로봇공학
김철수   1  4.2  컴퓨터공학  프로그래밍

## 6-5 실습 시나리오 - Kaggle을 활용한 데이터 수집 및 측정

- Kaggle([https://www.kaggle.com](https://www.kaggle.com)) 회원 가입
- Kaggle 접근 토큰 생성(API 키)

### Kaggle API 키 업로드

In [53]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle (1).json

{'kaggle (1).json': b'{"username":"youngchansong","key":"26fed9726b903c0b5f25152f31c9bf06"}'}

### Kaggle API 키 사용을 위한 Colab 환경 설정

In [54]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

### Kaggle 데이터셋 다운로드

In [57]:
!kaggle competitions download -c store-sales-time-series-forecasting

!unzip store-sales-time-series-forecasting.zip

Downloading store-sales-time-series-forecasting.zip to /content
100% 21.4M/21.4M [00:00<00:00, 140MB/s]

Archive:  store-sales-time-series-forecasting.zip
  inflating: holidays_events.csv
  inflating: oil.csv
  inflating: sample_submission.csv
  inflating: stores.csv
  inflating: test.csv
  inflating: train.csv
  inflating: transactions.csv

### Kaggle 데이터셋 DataFrame 로드 및 살펴보기

In [59]:
import pandas as pd

# Grocery Sales 데이터 DataFrame 로드
train = pd.read_csv('train.csv')
stores = pd.read_csv('stores.csv')
transactions = pd.read_csv('transactions.csv')
oil = pd.read_csv('oil.csv')
holidays_events = pd.read_csv('holidays_events.csv')

# 판매 데이터 살펴보기
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB

### Kaggle 데이터셋 측정

In [64]:
# 판매 데이터 기본 통계량
train.describe()

# 매장 데이터 기본 정보
stores.head()

# 원유 가격 데이터 기본 정보
#oil.head()

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4